# FWS CONFIG

global:                                             # GLOBAL SETTINGS
    theme-name: 'FWS Test'                    # set theme full name
    recovery-mode-emails:                           # change the fatal error handler email address from admin's to our internal
        - 'nick@forwardslashny.com'
        - 'boris@forwardslashny.com'
        - 'petar@forwardslashny.com'
        - 'dusan@forwardslashny.com'
    prevent-plugin-update:                          # only users logged in with declared email domain are allowed to add/update/remove plugins
        enable: true                                # enable/disable this rule
        domain: forwardslashny.com                  # allowed email domain
    cf7-custom-templates: true                      # enable/disable custom HTML and MJML templates for cf7 plugin
    acf-only-local-editing:                         # acf only possible to edit and manage on local environment
        enable: true                                # enable/disable this rule
        allowed-hosts:                              # list of allowed hosts
            - '.local'
            - '.docksal'
            - '.lndo.site'

acf-options-page:                                   # DEFINE ACF OPTIONS PAGES
    enable: true                                    # enable/disable options top level page
    subpages: ['SVG Icons']                         # list of options sub pages

acf-flexible-content:                               # DEFINE ACF FLEXIBLE CONTENT GROUPS AND FIELDS
    default-page-template:                          # define flexible content for default page template
        autoload: true                              # set whether or not to autoload this flexible content group
        field-name: 'Content'                       # filed name that will show on page
        location:                                   # set location where this field group will load
            param: 'page_template'
            value: 'default'
        hide-on-screen: [ 'the_content' ]           # set rules for default meta fields that should be hidden on a page
        layouts:                                    # set flex content layouts/blocks that will show for this group
            -
                title: 'Banner'
                group_id: 'group_5d70e7dfa2562'
            -
                title: 'Basic Block'
                group_id: 'group_5d70e7ea08bce'
            -
                title: 'Slider'
                group_id: 'group_5d70e7f775076'
            -
                title: 'Vue Block'
                group_id: 'group_5dcd6b37b67a4'
            -
                title: 'Banner Test'
                group_id: 'group_60c70568155cd'
            -
                title: 'Slider Test'
                group_id: 'group_60c7157bc06ab'
            -
                title: 'Top Product Categories Test'
                group_id: 'group_60c72269b0e24'
            -
                title: 'Latest Products Test'
                group_id: 'group_60c748958a402'
            -
                title: 'Story Block Test'
                group_id: 'group_60c75c6a603d1'
            -
                title: 'Team Test'
                group_id: 'group_60c76dc8f09ec'
            -
                title: 'Newsletter Test'
                group_id: 'group_60c76ce825e72'
styleguide:                                         # DEFINE STYLEGUIDE
    pages:                                          # set list of all pages defining their titles and urls
        -
            title: 'FE Homepage'
            url: '/fe-homepage/'
    colors:                                         # set list of all colors, matching variables in scss file
        - 'black'
        - 'grey-light'
        - 'grey-mid'
        - 'grey'
        - 'grey-dark'
        - 'white'
        - 'red'
        - 'green'
        - 'blue'
    icons:                                          # set list of all svg icons
        - 'ico-arrow-up'
        - 'ico-arrow-down'
        - 'ico-arrow-left'
        - 'ico-arrow-right'
        - 'ico-happy'
        - 'ico-lock'
        - 'ico-plus-circle'
        - 'ico-user'
        - 'ico-dog'
    fonts:                                          # set list of all fonts, matching variables in scss file
        -
            name: 'Open Sans'
            class: 'font-main'
    titles:                                         # set list of all special titles defining their classes and dummy text
        -
            text: 'This is Page Title'
            class: 'page-title'
        -
            text: 'This is Section Title'
            class: 'section-title'
    buttons:                                        # set list of all buttons defining their classes and dummy text
        -
            text: 'Normal'
            class: 'btn'
        -
            text: 'Green Button'
            class: 'btn btn--green'
        -
            text: 'Big Button'
            class: 'btn btn--big'
        -
            text: 'Big Green Button'
            class: 'btn btn--big btn--green'
